# Generated by Django 6.1.1 on 2026-09-24 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('captain_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('player_list', models.TextField(help_text='Enter player names separated by commas (11-15 players)')),
                ('payment_receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Village Premier League', max_length=200)),
                ('dates', models.CharField(default='October 10 - October 20', max_length=100)),
                ('location', models.CharField(default='Village Central Ground', max_length=200)),
                ('prize_pool', models.CharField(default='1st: ₹25,000 | 2nd: ₹10,000', max_length=200)),
                ('announcement', models.TextField(blank=True, default='Tournament registrations are now open!', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('tied', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.team')),
            ],
            options={
                'ordering': ['-points', '-won'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('venue', models.CharField(default='Main Village Ground', max_length=150)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=10)),
                ('team_a_score', models.CharField(blank=True, help_text='e.g. 120/4 (10 overs)', max_length=50, null=True)),
                ('team_b_score', models.CharField(blank=True, help_text='e.g. 115/8 (10 overs)', max_length=50, null=True)),
                ('margin_of_victory', models.CharField(blank=True, help_text='e.g. Won by 5 runs', max_length=100, null=True)),
                ('man_of_the_match', models.CharField(blank=True, max_length=100, null=True)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a', to='tournament.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='tournament.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='tournament.team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
