# Generated by Django 6.1.1 on 2026-09-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_remove_team_payment_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentsetting',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='tournamentsetting',
            name='prize_pool',
        ),
        migrations.AddField(
            model_name='tournamentsetting',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentsetting',
            name='first_prize',
            field=models.CharField(default='₹25,000 + Trophy', max_length=100),
        ),
        migrations.AddField(
            model_name='tournamentsetting',
            name='second_prize',
            field=models.CharField(default='₹15,000 + Trophy', max_length=100),
        ),
        migrations.AddField(
            model_name='tournamentsetting',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentsetting',
            name='third_prize',
            field=models.CharField(default='₹5,000 + Trophy', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournamentsetting',
            name='announcement',
            field=models.TextField(blank=True, default='Tournament registrations are open!', null=True),
        ),
    ]
