# Generated by Django 6.1.1 on 2026-09-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_remove_tournamentsetting_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsetting',
            name='contact_phone_1',
            field=models.CharField(default='+91 98765 43210', max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentsetting',
            name='contact_phone_2',
            field=models.CharField(default='+91 91234 56789', max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentsetting',
            name='full_address',
            field=models.TextField(default='Village Sports Complex, Near Gram Panchayat Office, District Central'),
        ),
    ]
